# Generated by Django 5.2 on 2025-05-10 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='criacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habito',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='habito',
            name='status',
            field=models.CharField(default='ativo', max_length=20),
        ),
    ]
