# Generated by Django 5.2 on 2025-05-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitos', '0002_habito_criacao_habito_descricao_habito_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habito',
            old_name='descricao',
            new_name='desc',
        ),
    ]
